### ISSUE TITLE
TypeError: el is null

### ISSUE THREAD

**Issue by SunboX** [gaia-components/gaia-list#3]
The `el` can be `null` here:

```javascript
proto.getChild = function(el) {
    return el.parentNode === this ? el : this.getChild(el.parentNode);
};
```
Source: https://github.com/gaia-components/gaia-list/blob/master/gaia-list.js#L147

![bildschirmfoto 2014-12-30 um 22 26 07](https://cloud.githubusercontent.com/assets/83344/5583076/545ee910-9073-11e4-8625-2af3d4a75044.png)

**Comment by kumarrishav** [comment]
@SunboX  close it now :)
